export const drivers = [
  { id: 1, name: "Unidentified Driver" },
  { id: 2, name: "AMARJIT SINGH" },
  { id: 3, name: "Beant Singh" },
  { id: 4, name: "Inderjeet Kaur" },
];

export const vehicles = [
  { id: 1, name: "Truck A" },
  { id: 2, name: "Truck B" },
  { id: 3, name: "Truck C" },
];

export const severity = [
  { id: 1, name: "Critical" },
  { id: 2, name: "High" },
  { id: 3, name: "Medium" },
  { id: 4, name: "Low" },
];

export const behaviours = [
  { id: 1, name: "Unsafe lane change" },
  { id: 2, name: "Close following" },
  { id: 3, name: "Lane cutoff" },
  { id: 4, name: "Ran red light" },
];

export const statuses = [
  { id: 1, name: "Pendint review" },
  { id: 2, name: "Coachable" },
  { id: 3, name: "Coached" },
  { id: 4, name: "Dismissed" },
];

export const eventTableData = [
  {
    id: 1,
    preview: "https://via.placeholder.com/100",
    behavior: "Close following",
    severity: "High",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/09/2024 01:14 AM",
    location: "Denver, CO",
    status: "Coachable",
  },
  {
    id: 2,
    preview: "https://via.placeholder.com/100",
    behavior: "Close following",
    severity: "High",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 11:44 PM",
    location: "20.7 mi W of Evergreen, CO",
    status: "Coachable",
  },
  {
    id: 3,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard braking",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 11:24 PM",
    location: "23.1 mi E of Vail, CO",
    status: "Pending review",
  },
  {
    id: 4,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard braking",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 11:21 PM",
    location: "20.2 mi E of Vail, CO",
    status: "Pending review",
  },
  {
    id: 5,
    preview: "https://via.placeholder.com/100",
    behavior: "Close following",
    severity: "High",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:24 PM",
    location: "16.9 mi W of Rifle, CO",
    status: "Coachable",
  },
  {
    id: 6,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard cornering",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:01 PM",
    location: "7.1 mi E of Clifton, CO",
    status: "Pending review",
  },
  {
    id: 6,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard cornering",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:01 PM",
    location: "7.1 mi E of Clifton, CO",
    status: "Pending review",
  },
  {
    id: 6,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard cornering",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:01 PM",
    location: "7.1 mi E of Clifton, CO",
    status: "Pending review",
  },
  {
    id: 6,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard cornering",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:01 PM",
    location: "7.1 mi E of Clifton, CO",
    status: "Pending review",
  },
  {
    id: 6,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard cornering",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:01 PM",
    location: "7.1 mi E of Clifton, CO",
    status: "Pending review",
  },
  {
    id: 6,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard cornering",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:01 PM",
    location: "7.1 mi E of Clifton, CO",
    status: "Pending review",
  },
  {
    id: 6,
    preview: "https://via.placeholder.com/100",
    behavior: "Hard cornering",
    severity: "Medium",
    driver: "AMARJIT SINGH",
    vehicle: "A02",
    date: "10/08/2024 09:01 PM",
    location: "7.1 mi E of Clifton, CO",
    status: "Pending review",
  },
];
